# Generated by Django 3.0.1 on 2019-12-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Nombre')),
                ('tortilla', models.CharField(choices=[('maiz', 'Maíz'), ('azul', 'Azul'), ('taquera', 'Taquera'), ('harina', 'Harina'), ('arabe', 'Árabe')], max_length=7, verbose_name='Tortilla')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Precio')),
            ],
        ),
    ]
