# Generated by Django 3.0.1 on 2019-12-21 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tacos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='taco',
            old_name='amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='taco',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Subtotal')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tacos.Cart')),
                ('taco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tacos.Taco')),
            ],
        ),
    ]
