# Generated by Django 3.0.1 on 2019-12-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tacos', '0002_auto_20191221_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='taco',
            name='image',
            field=models.URLField(default='example.com', verbose_name='URL de la imagen'),
            preserve_default=False,
        ),
    ]
