# Generated by Django 3.0.1 on 2019-12-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tacos', '0003_taco_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='taco',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='taco',
            name='tortilla',
            field=models.CharField(choices=[('maiz', 'Tortilla de Maíz'), ('azul', 'Tortilla Azul'), ('taquera', 'Tortilla Taquera'), ('harina', 'Tortilla Harina'), ('arabe', 'Tortilla Árabe')], max_length=7, verbose_name='Tortilla'),
        ),
    ]
