# Generated by Django 3.0.1 on 2019-12-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tacos', '0005_auto_20191221_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Subtotal'),
        ),
    ]
